export let flags = {
    "afghanistan": "png100px/af.png",
    "albania": "png100px/al.png",
    "algeria": "png100px/dz.png",
    "andorra": "png100px/ad.png",
    "angola": "png100px/ao.png",
    "antigua": "png100px/ag.png",
    "argentina": "png100px/ar.png",
    "armenia": "png100px/am.png",
    "australia": "png100px/au.png",
    "austria": "png100px/at.png",
    "azerbaijan": "png100px/az.png",
    "bahamas": "png100px/bs.png",
    "bahrain": "png100px/bh.png",
    "bangladesh": "png100px/bd.png",
    "barbados": "png100px/bb.png",
    "belarus": "png100px/by.png",
    "belgium": "png100px/be.png",
    "belize": "png100px/bz.png",
    "benin": "png100px/bj.png",
    "bhutan": "png100px/bt.png",
    "bolivia": "png100px/bo.png",
    "bosnia": "png100px/ba.png",
    "botswana": "png100px/bw.png",
    "brazil": "png100px/br.png",
    "brunei": "png100px/bn.png",
    "bulgaria": "png100px/bg.png",
    "burkina faso": "png100px/bf.png",
    "burundi": "png100px/bi.png",
    "cabo verde": "png100px/cv.png",
    "cambodia": "png100px/kh.png",
    "cameroon": "png100px/cm.png",
    "canada": "png100px/ca.png",
    "central african republic": "png100px/cf.png",
    "chad": "png100px/td.png",
    "chile": "png100px/cl.png",
    "china": "png100px/cn.png",
    "colombia": "png100px/co.png",
    "comoros": "png100px/km.png",
    "congo": "png100px/cg.png",
    "costa rica": "png100px/cr.png",
    "croatia": "png100px/hr.png",
    "cuba": "png100px/cu.png",
    "cyprus": "png100px/cy.png",
    "czech republic": "png100px/cz.png",
    "democratic republic of the congo": "png100px/cd.png",
    "denmark": "png100px/dk.png",
    "djibouti": "png100px/dj.png",
    "dominica": "png100px/dm.png",
    "dominican republic": "png100px/do.png",
    "ecuador": "png100px/ec.png",
    "egypt": "png100px/eg.png",
    "el salvador": "png100px/sv.png",
    "equatorial guinea": "png100px/gq.png",
    "estonia": "png100px/ee.png",
    "eswatini": "png100px/sz.png",
    "ethiopia": "png100px/et.png",
    "fiji": "png100px/fj.png",
    "finland": "png100px/fi.png",
    "france": "png100px/fr.png",
    "gabon": "png100px/ga.png",
    "gambia": "png100px/gm.png",
    "georgia": "png100px/ge.png",
    "germany": "png100px/de.png",
    "ghana": "png100px/gh.png",
    "greece": "png100px/gr.png",
    "grenada": "png100px/gd.png",
    "guatemala": "png100px/gt.png",
    "guinea": "png100px/gn.png",
    "guyana": "png100px/gy.png",
    "haiti": "png100px/ht.png",
    "honduras": "png100px/hn.png",
    "hungary": "png100px/hu.png",
    "iceland": "png100px/is.png",
    "india": "png100px/in.png",
    "indonesia": "png100px/id.png",
    "iran": "png100px/ir.png",
    "iraq": "png100px/iq.png",
    "ireland": "png100px/ie.png",
    "israel": "png100px/il.png",
    "italy": "png100px/it.png",
    "jamaica": "png100px/jm.png",
    "japan": "png100px/jp.png",
    "jordan": "png100px/jo.png",
    "kazakhstan": "png100px/kz.png",
    "kenya": "png100px/ke.png",
    "kiribati": "png100px/ki.png",
    "korea north": "png100px/kp.png",
    "korea south": "png100px/kr.png",
    "kosovo": "png100px/xk.png",
    "kuwait": "png100px/kw.png",
    "kyrgyzstan": "png100px/kg.png",
    "laos": "png100px/la.png",
    "latvia": "png100px/lv.png",
    "lebanon": "png100px/lb.png",
    "lesotho": "png100px/ls.png",
    "liberia": "png100px/lr.png",
    "libya": "png100px/ly.png",
    "liechtenstein": "png100px/li.png",
    "lithuania": "png100px/lt.png",
    "luxembourg": "png100px/lu.png",
    "madagascar": "png100px/mg.png",
    "malawi": "png100px/mw.png",
    "malaysia": "png100px/my.png",
    "maldives": "png100px/mv.png",
    "mali": "png100px/ml.png",
    "malta": "png100px/mt.png",
    "marshall islands": "png100px/mh.png",
    "mauritania": "png100px/mr.png",
    "mauritius": "png100px/mu.png",
    "mexico": "png100px/mx.png",
    "micronesia": "png100px/fm.png",
    "moldova": "png100px/md.png",
    "monaco": "png100px/mc.png",
    "mongolia": "png100px/mn.png",
    "montenegro": "png100px/me.png",
    "morocco": "png100px/ma.png",
    "mozambique": "png100px/mz.png",
    "myanmar": "png100px/mm.png",
    "namibia": "png100px/na.png",
    "nauru": "png100px/nr.png",
    "nepal": "png100px/np.png",
    "netherlands": "png100px/nl.png",
    "new zealand": "png100px/nz.png",
    "nicaragua": "png100px/ni.png",
    "niger": "png100px/ne.png",
    "nigeria": "png100px/ng.png",
    "north macedonia": "png100px/mk.png",
    "norway": "png100px/no.png",
    "oman": "png100px/om.png",
    "pakistan": "png100px/pk.png",
    "palau": "png100px/pw.png",
    "palestine": "png100px/ps.png",
    "panama": "png100px/pa.png",
    "papua new guinea": "png100px/pg.png",
    "paraguay": "png100px/py.png",
    "peru": "png100px/pe.png",
    "philippines": "png100px/ph.png",
    "poland": "png100px/pl.png",
    "portugal": "png100px/pt.png",
    "qatar": "png100px/qa.png",
    "romania": "png100px/ro.png",
    "russia": "png100px/ru.png",
    "rwanda": "png100px/rw.png",
    "saudi arabia": "png100px/sa.png",
    "senegal": "png100px/sn.png",
    "serbia": "png100px/rs.png",
    "singapore": "png100px/sg.png",
    "slovakia": "png100px/sk.png",
    "slovenia": "png100px/si.png",
    "solomon islands": "png100px/sb.png",
    "somalia": "png100px/so.png",
    "south africa": "png100px/za.png",
    "south sudan": "png100px/ss.png",
    "spain": "png100px/es.png",
    "sri lanka": "png100px/lk.png",
    "sudan": "png100px/sd.png",
    "suriname": "png100px/sr.png",
    "sweden": "png100px/se.png",
    "switzerland": "png100px/ch.png",
    "syria": "png100px/sy.png",
    "taiwan": "png100px/tw.png",
    "tajikistan": "png100px/tj.png",
    "tanzania": "png100px/tz.png",
    "thailand": "png100px/th.png",
    "togo": "png100px/tg.png",
    "tonga": "png100px/to.png",
    "tunisia": "png100px/tn.png",
    "turkey": "png100px/tr.png",
    "turkmenistan": "png100px/tm.png",
    "tuvalu": "png100px/tv.png",
    "uganda": "png100px/ug.png",
    "ukraine": "png100px/ua.png",
    "united arab emirates": "png100px/ae.png",
    "united kingdom": "png100px/gb.png",
    "united states": "png100px/us.png",
    "uruguay": "png100px/uy.png",
    "uzbekistan": "png100px/uz.png",
    "vanuatu": "png100px/vu.png",
    "vatican city": "png100px/va.png",
    "venezuela": "png100px/ve.png",
    "vietnam": "png100px/vn.png",
    "yemen": "png100px/ye.png",
    "zambia": "png100px/zm.png",
    "zimbabwe": "png100px/zw.png"
};